title: Exlamic!
description: Exlamic! is a bilingual audio archive exploring faith, text, and critical inquiry. Featuring Urdu and English recordings from open theological conversations, this podcast preserves the voices and questions often left unheard.
author:   إكسلاميك
email: adam.poszukiwacz@atomicmail.io
lang: ur
copyright: "&#x2117; &amp; &#xA9; 2025"
logo: /assets/img/logo.png

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
